name: sweet_nav_bar
description: This package is to build gradiant and floating Navigation Bar with a few lines of code.
version: 0.0.1
homepage: https://github.com/AbdallahAwd/sweet_nav_bar

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
